### ISSUE TITLE
[Feature] Use Chrome storage instead of localStorage to support auto-care 

### ISSUE THREAD

**Issue by techygrrrl** [folklorelabs/pockest-helper#92]
You can use the `chrome.storage` API ([docs](https://developer.chrome.com/docs/extensions/reference/api/storage)) instead of localStorage in the [PockestContext](https://github.com/folklorelabs/pockest-helper/blob/main/src/contexts/PockestContext.jsx#L48-L56) to allow syncing the data for your Chrome user. It works the same, more or less, the API is just async instead of synchronous.

## Why

It's useful to support auto-care when logging into a different computer, or different user on the same computer. Chrome extensions that use the Chrome storage APIs allow users to log into Chrome on Windows and Mac, for example, and persist the data there. This would be useful so that auto-care continues to work when you switch computers/users.

What I found is that the auto-care functionality does not work unless it's on the computer/computer user I initialized it in, but the stats in the panel seem to be up to date.

Obviously users should only run one tab at a time to avoid having it potentially duplicate auto-care instructions (e.g. close the tab, log into the other user, open the tab again to pick up where we left off and continue using auto-care).

What I find I need to do is log out of my other user and back into the current user to make sure auto-care kicks in and I haven't neglected the monster for too long. It would be great that since I have signed into the same user in Chrome on both, that I could pick up where I left off.

Thanks!

**Comment by Tera-ravyn** [comment]
Hello! Sorry to bother you, but I'm also having problems with auto-care not working at all. I'm using the extension in edge and everything is fine with the stats. Auto-care just doesn't seem to be working, but since it hasn't been working since the beginning I'm not quite sure which step I'm getting wrong. Can you explain exactly how "log out of my other user and back into the current user to make sure auto-care kicks in" restarts this auto-care feature? Thanks a lot!

**Comment by folklorelabs** [comment]
Great suggestion! I'll add this onto the to-do list :D

**Comment by folklorelabs** [comment]
> Hello! Sorry to bother you, but I'm also having problems with auto-care not working at all. I'm using the extension in edge and everything is fine with the stats. Auto-care just doesn't seem to be working, but since it hasn't been working since the beginning I'm not quite sure which step I'm getting wrong. Can you explain exactly how "log out of my other user and back into the current user to make sure auto-care kicks in" restarts this auto-care feature? Thanks a lot!

As for this issue, the chrome extension hasn't been tested in edge and won't get much support for it unfortunately. I know a few users have reported that it works for them in [the pockest discord](https://discord.gg/3m6x9mGCRe). Might be worth asking in there!

**Comment by folklorelabs** [comment]
After digging in a bit this will be a larger effort than I initially thought. We currently read the log (`window.localStorage.getItem('PockestHelperLog')`) for a few advanced monster plans and the log is far too big to store in Chrome storage based on the quota I'm seeing listed in the docs for `storage.sync` (8 KB per item).

So in order to get this working I'll need to refactor all this logic to duplicate this log info in a separate property on the state instead of getting that info directly from the log.

**Comment by folklorelabs** [comment]
> Great suggestion, thanks! I'll add this onto the to-do list :D

I spent some time tonight looking into this and ran into a couple issues:

1. We're currently using `localStorage` to save both the settings and the event log. Unfortunately the `chrome.storage.sync` has a very small quota for storage (< 8 KB per item) so we would only be able to sync settings. This isn't a blocker, but it does limit the functionality since logs would only be able to be stored locally.
2. It appears our extension would need to be published in the Chrome Web Store in order to get the `chrome.storage.sync` call to actually sync across devices. It otherwise functions as though we're using `chrome.storage.local` which adversely is essentially the same as if we continued using `window.localStorage`.
 
Seems a few others have run into similar issues. Here's a related stackoverlow: https://stackoverflow.com/questions/29567879/how-can-i-sync-localstorage-across-chrome-instances-or-use-chrome-storage-sync

Let me know if this is something you've run into and have a solution for, otherwise, I'll keep this in mind if we ever publish to the official store.

**Comment by techygrrrl** [comment]
Thanks for the update @folklorelabs! I didn't realize that Chrome storage required publishing to work (all my extensions that use it are published so maybe that's why I hadn't noticed the limitation). If you're unable to publish it and it won't work unless it's published, then it probably doesn't make sense to use this API.

Chrome storage does have that quota per item which is really annoying. That would be a huge pain to refactor to split it across items for the log, unless you periodically clear the log—would the logs for a lifetime of a single monster until departure fit? Then old logs could be cleared when starting a new monster. The auto-care instructions should fit.

I appreciate you looking into this. It sounds like it may not make sense to do this migration if you're not planning on publishing it. I guess if I really wanted to use this across machines, I could copy the localStorage values over onto my other machine. I haven't tried that but I assume it could work.

**Comment by folklorelabs** [comment]
Thanks, I'll close this out for now but will keep it in mind if we ever decide to publish the addon.
